<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Company>Gibbed</Company>
    <Authors>Gibbed</Authors>
    <Description></Description>
    <Copyright>Copyright © Gibbed 2019</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <Version>7.0.0</Version>
    <AssemblyVersion>7.0.0.0</AssemblyVersion>
    <FileVersion>7.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Pink.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/gibbed/SteamAchievementManager/</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>

</Project>