<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <ApplicationIcon>SAM.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SAM.Picker</AssemblyName>

    <StartupObject>SAM.Picker.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SAM.API\SAM.API.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <PropertyGroup>
      <SteamPath>$([MSBuild]::GetRegistryValue('HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam', 'InstallPath'))</SteamPath>
    </PropertyGroup>
    <ItemGroup Condition="'$(SteamPath)' != ''">
      <SteamFiles Include="$(SteamPath)\steamclient.dll;$(SteamPath)\tier0_s.dll;$(SteamPath)\vstdlib_s.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(SteamFiles)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" ContinueOnError="true" Condition="'$(SteamPath)' != ''" />
  </Target>

</Project>
