<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x86</Platforms>
    <Platform>x86</Platform>
    <LangVersion>latest</LangVersion>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyTitle>Steam Achievement Manager</AssemblyTitle>
    <Company>Gibbed</Company>
    <Authors>Gibbed</Authors>
    <Description>A manager for game achievements in Steam.</Description>
    <Copyright>Copyright © Gibbed 2019</Copyright>
    <Version>7.0.42</Version>
    <ApplicationIcon>Blank.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RepositoryUrl>https://github.com/gibbed/SteamAchievementManager/</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="DoubleBufferedListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Manager.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAM.API\SAM.API.csproj" />
  </ItemGroup>
</Project>